apiVersion: v1
kind: Service
metadata:
  name: umkm-app-api-lb-1
  labels:
    app.kubernetes.io/name: umkm-app-api
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: umkm-app-api
    tier: backend
  ports:
  - name: http
    port: 9900
    protocol: TCP
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: umkm-app-api-lb-2
  labels:
    app.kubernetes.io/name: umkm-app-api
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: umkm-app-api
    tier: backend
  ports:
  - name: http
    port: 9900
    protocol: TCP
    targetPort: 8080